name: Java CI with Gradle
on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle And Test
      uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

    - name: Build with Gradle Wrapper
      run: ./gradlew clean test

    - name: Get branch name
      id: branch-name
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_OUTPUT
        else
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: run deploy script
      env:
        SSH_SERVER_INFO: ${{ secrets.SSH_SERVER_INFO }}
        PEM_KEY: ${{ secrets.PEM_KEY }}
        SCRIPT_PATH: ${{ secrets.SCRIPT_PATH }}
      run: |
        echo "$PEM_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key $SSH_SERVER_INFO "bash $SCRIPT_PATH ${{ steps.branch-name.outputs.BRANCH_NAME }}"
